#!/bin/bash

. "$(dirname "$0")"/helpers/init.sh
helper mt_split2mono_map_llvm

usage() {
    printf "%s\n" \
        "usage: $(print_cmdname) <commit-ish>" \
        "" \
        "  extract SVN revisions from <commit-ish> and all ancestors" \
        "  and map them to the canonical commit in the svn2git.db"
}

[ "$#" -ge 1 ] || usage_error "missing <commit-ish>"
[ "$#" -eq 1 ] || usage_error "too many positional args"

mt_split2mono_init &&
mt_split2mono_map_llvm "$@" &&
mt_split2mono_save
