#!/bin/bash

. "$(dirname "$0")"/helpers/init.sh
helper mt_llvm_svn

usage() { echo "usage: $(print_cmdname) <commit>"; }

[ "$#" -ge 1 ] || usage_error "missing <commit>"
[ "$#" -eq 1 ] || usage_error "too many positional args"

mt_llvm_svn "$@"
