#!/bin/bash

. "$(dirname "$0")"/helpers/init.sh
helper mt_split2mono
helper mt_split2mono_interleave_commits

usage() {
    printf "%s\n"                                                            \
        "usage: $(print_cmdname) <branch> "                                  \
        "           [--repeat <upstream>]..."                                \
        "           [--skip <skip>]..."                                      \
        "           <ref>:<dir>..."                                          \
        "   <branch>      the branch to interleave"                          \
        "   <upstream>    monorepo upstream to interleave with <ref>:<dir>"  \
        "   <ref>...      the refs for split branches to combine"            \
        "   <dir>...      the dirs for each split branch; '-' for root"      \
        ""                                                                   \
        "   optimization:"                                                   \
        "   <skip>...     split <ref>s in the upstreams"                     \
        ""                                                                   \
        "   updates these:"                                                  \
        "   refs/heads/mt/<branch>/<dir>/mt-split -> <split-commit>"
}

main() {
    [ $# -ge 1 ] || usage_error "missing <branch>"
    [ $# -ge 2 ] || usage_error "missing <ref>:<dir>..."

    mt_split2mono_init &&
    translate_branch "$@" &&
    mt_split2mono_save
}

translate_branch() {
    local branch
    local pos=0
    local repeat=
    local -a skips
    local -a refdirs
    local value=
    while [ $# -gt 0 ]; do
        case "$1" in
            --help)
                usage
                exit 0
                ;;
            --repeat|--repeat=*)
                parse_cmdline_option --repeat repeat
                shift $?
                ;;
            --skip|--skip=*)
                parse_cmdline_option --skip value
                shift $?
                skips=( "${skips[@]}" "$value" )
                ;;
            -*)
                usage_error "unknown option '$1'"
                ;;
            *)
                if [ $pos -eq 0 ]; then
                    branch="$1"
                else
                    refdirs=( "${refdirs[@]}" "$1" )
                fi
                pos=1
                shift
                ;;
        esac
    done
    [ -n "$branch" ] || usage_error "missing <branch>"
    branch="${branch#refs/heads/}"

    [ ${#refdirs[@]} -gt 0 ] || usage_error "missing <ref>:<dir>"
    mt_split2mono_check_refdirs "${refdirs[@]}"
    mt_split2mono_check_skips "${skips[@]}"

    [ -z "$repeat" ] || error "--repeat not implemented"

    local current
    current=$(run git --hide-errors rev-parse --verify \
        refs/heads/$branch^{commit}) ||
        current=0000000000000000000000000000000000000000


    mt_split2mono_list_new_split_commits "$branch" "${refdirs[@]}" |
    mt_split2mono_interleave_commits "$branch" "$repeat" "${refdirs[*]}" |
    update_refs "$branch" "$current" "${refdirs[*]}" ||
        error "failure interleaving commits"
}

update_refs() {
    local branch="${1#refs/heads/}"
    local current="$2"
    local refdirs="$3"
    local head sha1dirs
    read head sha1dirs

    # Detect failure.  No reason to report a new error.
    [ -n "$head" ] || return 1

    local ref=refs/heads/$branch
    log "Updating $branch to $head"
    run git update-ref $ref $head $current ||
        error "failed to update $branch"
    local sd sha1 rd r d
    for rd in $refdirs; do
        r=${rd%:*}
        d=${rd#*:}
        ref=refs/heads/$branch/${r#refs/heads/}/mt-split
        sha1=
        for sd in $sha1dirs; do
            [ "$d" = "${sd#*:}" ] || continue
            sha1=${sd%:*}
            break
        done
        [ -n "$sha1" ] || error "missing output sha1 for $rd"
        if [ $sha1 = 0000000000000000000000000000000000000000 ]; then
            sha1=$(run git --hide-errors rev-parse --verify $ref^{commit})
            [ -z "$sha1" ] || error "$ref had a value, but now does not"
            continue
        fi
        run git update-ref $ref $sha1 ||
            error "failed to update $ref"
    done
}

main "$@"
