#!/bin/bash

. "$(dirname "$0")"/helpers/init.sh
helper mt_split2mono

usage() { echo "usage: $(print_cmdname) <sha1>"; }

[ "$#" -ge 1 ] || usage_error "missing <sha1>"
[ "$#" -eq 1 ] || usage_error "too many positional args"

mt_split2mono_init &&
mt_split2mono "$@"
