#!/bin/bash

. "$(dirname "$0")"/helpers/init.sh
helper mt_split2mono
helper mt_llvm_svn2git
helper mt_list_commits

usage() {
    printf "%s\n" \
        "usage: $(print_cmdname) [options] <branch> <ref>:<dir>..."         \
        ""                                                                  \
        "   <branch>      the branch to interleave"                         \
        "   <ref>         a ref to interleave commits from"                 \
        "                   '%<ref>[{no-pass}]' to repeat commits"          \
        "                     from <upstream> (optionally, without passing" \
        "                     other refs)"                                  \
        "                   '-' if there is no relevant split repo"         \
        "   <dir>         the name of the top-level tree to put <ref> into" \
        "                   '-' for root (splat contents)"                  \
        ""                                                                  \
        "  --check-for-work"                                                \
        "                 print <branch> if there's work (but don't do it)"
}

main() {
    local branch
    local -a refdirs
    parse_cmdline "$@" || return 1

    # Only initialize split2mono db if we will interleave commits.
    # Initializing the blob is not free and there's no point.
    check_for_work || mt_split2mono_init || return 1
    translate_branch "$@" || return 1
    check_for_work || mt_split2mono_save || return 1
}

CHECK_FOR_WORK=0
check_for_work() { [ ! "${CHECK_FOR_WORK:-0}" = 0 ]; }

parse_cmdline() {
    [ $# -ge 1 ] || usage_error "missing <branch>"
    [ $# -ge 2 ] || usage_error "missing <ref>:<dir>..."
    local pos=0
    while [ $# -gt 0 ]; do
        case "$1" in
            --help)
                usage
                exit 0
                ;;
            --check-for-work) CHECK_FOR_WORK=1; shift ;;
            *:*)
                [ $pos -ne 0 ] || usage_error "invalid branch name '$1'"
                refdirs=( "${refdirs[@]}" "$1" )
                shift
                ;;
            -*)
                usage_error "unknown option '$1'"
                ;;
            *)
                [ $pos -eq 0 ] || usage_error "unexpected argument '$1'"
                branch="$1"
                pos=1
                shift
                ;;
        esac
    done
    [ -n "$branch" ] || usage_error "missing <branch>"
    branch="${branch#refs/heads/}"

    [ ${#refdirs[@]} -gt 0 ] || usage_error "missing <ref>:<dir>"
}

translate_branch() {
    local current
    current=$(run --hide-errors git rev-parse --verify \
        refs/heads/$branch^{commit}) ||
        current=$ZERO_SHA1

    local r d rd ref sha1
    local -a listdirs # refs to list commits of and for which directory
    local -a repeated # directories getting repeated
    local repeated_root # the root is getting repeated
    local -a sha1dirs # command-line for split2mono interleave-commits
    local repeat suffix
    local nopass
    local declared # all declared directories, except '-'
    for rd in "${refdirs[@]}"; do
        r="${rd%:*}"
        d="${rd##*:}"
        suffix="$d/mt-split"

        # Gather all the declared directories for list_new_commits.
        [ "$d" = - ] || declared="$declared${declared:+ }$d"

        if [ "${r:0:1}" = % ]; then
            [ -z "$repeat" ] || [ "$repeat" = "${r:1}" ] ||
                error "mismatched repeat in '$rd' (expected: '$repeat')"
            sha1dirs=( "${sha1dirs[@]}" "%:$d" )

            if [ "$d" = - ]; then
                repeated_root=1
            else
                repeated=( "${repeated[@]}" "$d/" )
            fi

            [ -z "$repeat" ] || continue
            repeat="${r:1}"
            suffix=mt-repeat r="$repeat" d=%
            rd="${r%\{no-pass\}}:$d"
            [ "$rd" = "$r:$d" ] || nopass=1
        fi

        ref=refs/heads/mt/$branch/$suffix
        sha1=-
        [ "$r" = - ] ||
            sha1=$(run --hide-errors git rev-parse --verify $ref^{commit}) ||
            sha1=$ZERO_SHA1
        sha1dirs=( "${sha1dirs[@]}" "$sha1:$d" )

        [ ! "$r" = - ] || continue
        listdirs=( "${listdirs[@]}" "$rd" )
    done

    # Figure out the latest commit date coming in.
    local until ct
    if [ -n "$nopass" ]; then
        until=0
        for rd in "${refdirs[@]}"; do
            [ "${rd:0:1}" = % ] && continue
            [ "${rd:0:1}" = - ] && continue
            r="${rd%:*}"
            ct=$(run git log --format=%ct -1 "$r") ||
                error "failed to extract committer date from ref '$r'"
            [ $until -ge $ct ] || until=$ct
        done
    fi

    list_new_commits "$branch" "${listdirs[*]}" "${repeated[*]}" $until |
    process_new_commits ||
        exit 1
}

process_new_commits() {
    if check_for_work; then
        local num_commits
        while read num_commits; do
            # If there are no commits, continue.  Ignore errors from
            # non-integer input for now.
            [ "$num_commits" -eq 0 ] 2>/dev/null && continue

            # Validate commit count.
            [ "$num_commits" -ne 0 ] 2>/dev/null ||
                error "--check-for-work: invalid number of commits"

            # Report that there's work to do and then exit, after eating up
            # remaining input to prevent a broken pipe.
            printf "%s\n" "$branch"
            cat >/dev/null
            exit 0
        done

        # There's nothing to do.
        return 0
    fi

    interleave_commits "$branch" "${sha1dirs[*]}" |
    update_refs "$branch" "$current" "${sha1dirs[*]}" ||
        error "failure interleaving commits"
}

list_new_commits() {
    local commit_lister=mt_list_commits
    ! check_for_work || commit_lister=mt_count_commits

    local branch="$1"
    local refdirs="$2"
    local repeated="$3"
    local until=$4
    local rd r d head tail format tailref headref suffix extra nots
    local add_repeated_root extra_repeated
    for rd in $refdirs; do
        r="${rd%:*}"
        d="${rd##*:}"

        extra= nots= add_repeated_root=
        if [ "$d" = % ]; then
            run --hide-errors git rev-parse --verify $branch^{commit} \
                >/dev/null &&
                nots=$branch
            suffix=mt-repeat
            extra="--first-parent${until:+ --until=}$until --"
            extra="$extra${repeated:+ }$repeated"
            add_repeated_root=$repeated_root
        else
            suffix="$d/mt-split"
        fi
        tailref="refs/heads/mt/$branch/$suffix"
        headref="$r"
        tail="$(run --hide-errors git rev-parse --verify $tailref^{commit})"
        head="$(run --hide-errors git rev-parse --verify $headref^{commit})" ||
            error "invalid ref '$headref' from '$rd'"
        [ "$tail" = "$head" ] && continue

        # TODO: add a testcase for d of '-', which requires '--' here.
        nots="$nots${nots:+ }$(run git show-ref -- $suffix |
            grep refs/heads/mt/ | awk '{print $2}')"

        if [ -n "$add_repeated_root" ]; then
            # List all the top-level paths touched in the root, so we can
            # select those commits to repeat.
            local begin= decl=
            begin="BEGIN {"
            for decl in $declared; do
                begin="$begin ignore[\"$decl\"] = 1;"
            done
            begin="$begin }"
            # This is missing the existing "extra" flags, but it's okay if we
            # get an over-approximation of changed paths here.
            extra_repeated="$(run git log --format= --name-only $headref \
                --not $nots | sed -e 's,/.*,,' | sort -u |
                run awk "$begin"' ignore[$0] { next } { print }')"
            extra="$extra${extra_repeated:+ }$extra_repeated"
        fi

        $commit_lister "$d" $headref --not $nots $extra ||
            error "failed to list new commits for $rd"
    done
}

interleave_commits() {
    local branch="$1"
    local sha1dirs="$2"

    ref=refs/heads/${branch#refs/heads/}
    local head
    head=$(run --hide-errors git rev-parse --verify $ref^{commit}) ||
        head=$ZERO_SHA1

    local svn2git split2mono
    split2mono="$(build_executable split2mono)" ||
        error "could not build split2mono"
    run "$split2mono" interleave-commits \
        "$MT_DB_SPLIT2MONO_DB" "$MT_DB_SVN2GIT_DB" "$head" $sha1dirs
}

update_refs() {
    local branch="${1#refs/heads/}"
    local current="$2"
    local old_sha1dirs="$3"
    local new_sha1dirs head
    read head new_sha1dirs
    [ "${VERBOSE:-0}" = 0 ] || log "translation: $head $new_sha1dirs"

    # Detect failure.  No reason to report a new error.
    [ -n "$head" ] || return 1

    local ref=refs/heads/$branch
    {
        log "Updating $branch => $head"
        run printf "update %s %s %s\n" $ref $head $current
        local old_sha1 new_sha1 new_sd sd d
        for sd in $old_sha1dirs; do
            d=${sd#*:}
            old_sha1=${sd%:*}
            new_sha1=
            case "$old_sha1" in
                -|%) continue ;;
                *)   true ;;
            esac
            if [ "$d" = % ]; then
                ref=refs/heads/mt/$branch/mt-repeat
            else
                ref=refs/heads/mt/$branch/$d/mt-split
            fi
            for new_sd in $new_sha1dirs; do
                [ "$d" = "${new_sd#*:}" ] || continue
                new_sha1=${new_sd%:*}
                break
            done
            if [ -z "$new_sha1" ]; then
                printf "poison update-ref\n"
                error "missing output sha1 for '$d'"
            fi
            if [ $new_sha1 = $ZERO_SHA1 -a \
                ! "$new_sha1" = "$old_sha1" ]; then
                printf "poison update-ref\n"
                error "internal: new value for $ref is $new_sha1" \
                    "but it was $old_sha1"
            fi
            if [ "$new_sha1" = "$old_sha1" ]; then
                log " - ${ref#refs/heads/} == $new_sha1"
                run printf "verify %s %s\n" $ref $new_sha1
            else
                log " - ${ref#refs/heads/} => $new_sha1"
                run printf "update %s %s %s\n" $ref $new_sha1 $old_sha1
            fi
        done
    } | run git update-ref --stdin ||
        error "failed to update $branch and $refdirs"
}

main "$@"
