#!/bin/bash

NONGIT_OK=1
. "$(dirname "$0")"/helpers/init.sh
helper canonicalize_path

usage() {
    printf "%s\n"                                                             \
        "usage: $(print_cmdname) [options] <downstream>"                      \
        ""                                                                    \
        "   --config-dir=<dir> Config directory (default: $DEFAULT_CONFIG_DIR)"  \
        "   --git-dir=<dir>    Git directory (default: $DEFAULT_GIT_DIR)"     \
        "   --[no-]verbose     Print out what will happen"                    \
        "   --dry-run          Don't do anything"
}

DEFAULT_CONFIG_DIR="$(
    relative_canonicalize_path "$APPLE_LLVM_LIBEXEC_DIR/../../fwd-config")"
DEFAULT_GIT_DIR=apple-llvm-fwd-repo.git

is_not_same_url() {
    local url="$1"
    local existing="$2"
    if [ "$url" = "$existing" ]; then
        return 1
    fi
    return 0
}

fwd_setup() {
    GIT_DIR="$(canonicalize_path "$GIT_DIR")"
    FWD_CONFIG="$(canonicalize_path "$CONFIG_DIR/$NAME.fwd-config")"
    [ -f "$FWD_CONFIG" ] ||
        usage_error "config for '$NAME' not found at '$FWD_CONFIG'"

    # Always change directory.
    log "Updating remotes up and syncing $GIT_DIR"
    if [ -d "$GIT_DIR" ]; then
        run --dry cd "$GIT_DIR" || error "failed to enter '$GIT_DIR'"
    else
        run --dry mkdir -p "$GIT_DIR" || error "failed to make '$GIT_DIR'"
        run --dry git init || error "failed to create '$GIT_DIR'"
    fi

    local -a remotes
    for remote in $(run cat "$FWD_CONFIG" |
        run awk '$1=="remote"{print $2 ":" $3}'); do
        name="${remote%%:*}"
        url="${remote#*:}"
        existing="$(run --dry git remote -v |
        run --dry awk -v n="$name" -v e="(fetch)" '$1==n&&$3==e{print $2}')"
        existing_push="$(run --dry git remote -v |
        run --dry awk -v n="$name" -v e="(push)" '$1==n&&$3==e{print $2}')"
        if [ -z "$existing" ]; then
            run --dry git remote add "$name" "$url"
        elif is_not_same_url $url $existing; then
            error "remote '$name' exists with fetch URL '$existing';" \
            "refusing to set-url to '$url'"
        elif [ -n $existing_push ] && is_not_same_url $url $existing_push; then
            error "remote '$name' exists with push URL '$existing';" \
            "refusing to set-url to '$url'"
        fi
        log "  - $name $url"
        run --dry git fetch "$name" ||
            error "failed to fetch from '$name'"
    done
}

CONFIG_DIR="$DEFAULT_CONFIG_DIR"
GIT_DIR=$DEFAULT_GIT_DIR
SETUP=1
NAME=
while [ $# -gt 0 ]; do
    case "$1" in
        --config-dir|--config-dir=*)
            parse_cmdline_option --config-dir CONFIG_DIR "$@"
            shift $?
            [ -n "$CONFIG_DIR" ] || usage_error "--config-dir cannot be empty"
            [ -d "$CONFIG_DIR" ] || usage_error "'$CONFIG_DIR' not a directory"
            ;;
        --git-dir|--git-dir=*)
            parse_cmdline_option --git-dir GIT_DIR "$@"
            shift $?
            [ -n "$GIT_DIR" ] || usage_error "--git-dir cannot be empty"
            ;;
        --dry-run)  DRY_RUN=1; shift ;;
        --verbose)    VERBOSE=1; shift ;;
        --no-verbose) VERBOSE=0; shift ;;
        --help|--usage|-h) usage; exit 0 ;;
        -*) usage_error "unknown option '$1'" ;;
        *)
            [ -z "$NAME" ] || usage_error "too many positional arguments"
            [ -n "$1" ] || usage_error "empty name for downstream"
            NAME="$1"
            shift
            ;;
    esac
done

[ -n "$NAME" ] || usage_error "missing name of fwd-config"

fwd_setup || exit 1

log "Forwarding refs"
cat "$FWD_CONFIG" | awk '$1 == "push" {print $2, $3}' |
while read remote refspec; do
    log "  - $remote $refspec"
    run --dry git push "$remote" "$refspec" || error "failed to push '$3' to '$2'"
done
exit 0
