@NonCPS
def setDescription() {
    def item = Jenkins.instance.getItemByFullName(env.JOB_NAME)
    item.setDescription("""Build, Test and Lint the apple-llvm monorepo tools and docs.
    DRI: Alex Lorenz and Chris Matthews.
    """)
    item.save()
}

setDescription()

pipeline {
    agent {label 'MonorepoToolsNode'}
    stages {
        stage('Run Tests') {

            steps {
                sh '''
                cd test
                make -k all
                '''
            }
        }
        stage('Make Docs') {

            steps {

                sh '''
                cd docs
                make -k html
                '''
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
